### ISSUE TITLE
Change the Minecraft Wiki link in the wiki.

### ISSUE THREAD

**Issue by bauerbach** [TheNewEconomy/PhantomWorlds#5]
The link to the Minecraft Wiki's generator settings page on the PW wiki's Commands and Permissions page still points to FANDOM. However, the Minecraft Wiki recently became independent and moved to http://minecraft.wiki.

**Comment by creatorfromhell** [comment]
> The link to the Minecraft Wiki's generator settings page on the PW wiki's Commands and Permissions page still points to FANDOM. However, the Minecraft Wiki recently became independent and moved to http://minecraft.wiki.

The wiki has been updated https://theneweconomy.github.io/docs/pw-docs/user/commands/
